default:
  options:
    videomode: max-1280x720

amigacdtv:
  emulator: libretro
  core:     uae4arm
nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
psx:
  options:
    gpu_software: true
    gfxbackend: Software
atomiswave:
  emulator: libretro
  core:     flycastvl
dreamcast:
  emulator: libretro
  core:     flycastvl
naomi:
  emulator: libretro
  core:     flycastvl
flash:
  emulator: lightspark
  core:     lightspark

