default:
  options:
    rewind:      false
    hud_support: false
    video_threaded: true
    videomode: max-1280x720
    smooth:         false
    audio_latency:  96
    # menu retroarch
    retroarch.menu_driver: rgui

gba:
  emulator: libretro
  core:     gpsp
nds:
  emulator: drastic
  core:     drastic
mame:
  emulator: libretro
  core:     imame4all
gamegear:
  emulator: libretro
  core:     picodrive
mastersystem:
  emulator: libretro
  core:     picodrive
megadrive:
  emulator: libretro
  core:     picodrive
segacd:
  emulator: libretro
  core:     picodrive
satellaview:
  emulator: libretro
  core:     pocketsnes
snes:
  emulator: libretro
  core:     pocketsnes
snes-msu1:
  emulator: libretro
  core:     pocketsnes
c64:
  emulator: libretro
  core:     vice_x64
c20:
  emulator: libretro
  core:     vice_xvic
c128:
  emulator: libretro
  core:     vice_x128
cplus4:
  emulator: libretro
  core:     vice_xplus4
pet:
  emulator: libretro
  core:     vice_xpet
atari2600:
  emulator: libretro
  core:     stella2014
fbneo:
  emulator: libretro
  core:     fbalpha
neogeo:
  emulator: libretro
  core:     fbalpha
scummvm:
  emulator: libretro
  core:     scummvm
