default:
  options:
    video_threaded: true
    retroarch.menu_driver: rgui

nds:
  emulator: drastic
  core:     drastic
fmtowns:
  emulator: libretro
  core:     mame
atomiswave:
  emulator: libretro
  core:     flycastvl
dreamcast:
  emulator: libretro
  core:     flycastvl
naomi:
  emulator: libretro
  core:     flycastvl
flash:
  emulator: lightspark
  core:     lightspark

