nds:
  emulator: libretro
  core:     melonds
fmtowns:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
model3:
  emulator: supermodel
  core:     supermodel-legacy
  options:
    videomode: max-1920x1080
    decorations: none
    hud_support: none

