name: Trigger regmsg compiler

on:
  push:
    paths:
      - 'package/system/reglinux-msg/**'
      - 'package/boot/plymouth/**'

jobs:
  trigger-regmsg-workflow:
    runs-on: ubuntu-latest
    name: Trigger remote workflow
    steps:
      - name: Trigger regmsg compilation workflow
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REG_TOKEN }}" \
          https://api.github.com/repos/REG-Linux/regmsg-binaries/dispatches \
          -d '{"event_type":"trigger-workflow"}'
