name: Trigger llvm compiler

on:
  push:
    branches:
      - wip
    paths:
      - '.gitmodules'
      - 'custom/package/*llvm*/**'
      - '.github/workflows/build-toolchain-and-llvm.yaml'

jobs:
  trigger-llvm-workflow:
    runs-on: ubuntu-latest
    name: Trigger remote workflow
    steps:
      - name: Trigger llvm compilation workflow
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REG_TOKEN }}" \
          https://api.github.com/repos/REG-Linux/REG-llvm-binaries/dispatches \
          -d '{"event_type":"trigger-workflow"}'
